### ISSUE TITLE
Image download issue.

### ISSUE THREAD

**Issue by budhajeewa** [timofeysie/serene-brushlands#105]
>[...] one problem is that on the site, the work by Debra Murray has the Ceramic Bagu image, but on the downloaded document it has a different image. The image and data for the artworks needs to be preserved for the download. The asset reference number is not unique, so we would like the position in the uploaded Word document to work as a unique position identifier for the site data.

— @timofeysie

**Comment by budhajeewa** [comment]
@timofeysie Can you explain more about this?

> so we would like the position in the uploaded Word document to work as a unique position identifier for the site data

Asset reference number is act as unique key for the artwork already.

**Comment by timofeysie** [comment]
The asset Reference number is NOT unique as in the past a number of pictures purchased at one time were added to the asset register as a single lump sum with a single reference number.

**Comment by budhajeewa** [comment]
@timofeysie you can test this at http://45.55.52.23
