### ISSUE TITLE
Upload "empty response" needs to recover and show a meaningful message.

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/serene-brushlands#107]
When going to the gallery tab, the spinner is endless and this error is in the console.
GET http://45.55.52.23/get-artworks net::ERR_EMPTY_RESPONSE

The product owner stated that he did this:
*After making minor changes to the WORD document several days ago I started the upload process but had to log out while it was “processing” the uploaded file.*
 
*I left the computer on overnight but when I tried to access the data from home I just got the activity spiral so have left it running too (after logging out of trinura.cf)*

This may be a corrupted formatting issue, but we should still try to recover and show a meaningful message.

**Comment by budhajeewa** [comment]
@timofeysie 
For recover old data if upload corrupted we have to first back-up all data in database before upload.

If new upload data was corrupted we can restore data from back-up database.

We can have button in upload page to `Restore data to previous version`.

Should I implement this?

**Comment by timofeysie** [comment]
Isn't this what the 'Use backup' feature is for?

**Comment by timofeysie** [comment]
Can you determine the cause of the upload corruption and create an automatic fallback in that scenario?

**Comment by budhajeewa** [comment]
Current implementation of `Use backup` is saving currently uploading data to JSON file. If there is a corruption in data uploaded backup file also having corrupted data. 

What we need to do is save current data (which is not corrupted) to JSON file and then replace database with uploaded data. If corruption occurs we can simply use use backup button to write data in JSON file to database. 

> Can you determine the cause of the upload corruption and create an automatic fallback in that scenario?

There is no way to determine what cause the corruption last time. Best solution I can think is create implement `Use backup` feature so client can restore backup data.

**Comment by timofeysie** [comment]
I still think it would be a good idea to indicate what kind of problem there was during parsing.
Ie: duplicate reference numbers, bad formatting on image xxx, network failure, etc whatever problem you can determine via the parse function in the node file.
The backup feature will not help improving the source document.  The download feature was supposed to assist with this, but it can't help if the upload fails.  So information about an upload failure is better than a backup.  It would be difficult to "roll back" changes to a Word document.

**Comment by budhajeewa** [comment]
> Ie: duplicate reference numbers, bad formatting on image xxx, network failure, etc whatever problem you can determine via the parse function in the node file.

Okay I will look into it
