### ISSUE TITLE
Must allow deep linking using reference numbers

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/serene-brushlands#108]
A major feature of the app requires writing NFC tags with the artwork URL so that that page can be viewed by scanning the tag.  Currently the artwork reference number does not appear in the url.

This means also that we cannot use the page position of works as the work id, as works that are deleted from the source document would then change the order of the artworks.

The document owner will ensure that all reference numbers are unique.  We should also catch duplicate reference number situations and alert the user of the artworks with a duplicate reference number.

**Comment by timofeysie** [comment]
I changed the setting for URL Forwarding to forward mode instead of "Frame Cloaking" which I think was the problem.  Still unable to test as the current document is corrupted.

**Comment by timofeysie** [comment]
The link for Gularungnardi:
http://45.55.52.23/#/view3/229
Has number 232 in the Artworks tab, and the document Asset Reference No is 232.
Since the url to the artwork must be written to NFC tags, it should not change in the future, other wise the tags that change will need to be re-written.

Therefore, since the product owner will guarantee that each reference number will be unique, these should be used for the deep linking.  If a document is uploaded with a repeat reference number, the user should be alerted to this problem.  This is related to issue #107.

**Comment by timofeysie** [comment]
I think it would be best to use the asset reference number + image name for the artwork id.  It would look like this: FF-0054-image-71, FF-0054-image-72, FF-0054-image-73, FF-0054-image-74, FF-0054-image-75.  
This needs to be used as the URL (artwork link) that will be written to an NFC tag placed next to the artwork.  Then it must not change so that whenever a new document is uploaded, the same URL/artwork link will be created.  Otherwise the tags would have to be re-written which is a pain.

**Comment by budhajeewa** [comment]
There isn't a way to get image name from the document. As for the current implementation document is checked before upload uniqueness of the `asset reference number`. So artwork link wouldn't not be changed if new document is uploaded. (`http://45.55.52.23/#/view3/{asset reference number}`)

**Comment by timofeysie** [comment]
OK.  I think the image names, as shown in the collection data page, are actually generated by Word and represent the order in the document.  So if an artwork is sold and removed from the document, then the order would change and the works after that would then have different links.
Let's stay with the Asset Reference number and let the product owner ensure that they will be unique.  The error reporting feature will aid in this.
