### ISSUE TITLE
net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/serene-brushlands#18]
When uploading a new document, the status will go to 100%, and a message saying please wait while the document is being processed will not go away and the upload did not work.
The error was:
```
angular.js:11028 GET http://45.55.52.23/artworks net::ERR_CONTENT_LENGTH_MISMATCH(anonymous function) @ angular.js:11028sendReq @ angular.js:10821serverRequest @ angular.js:10531processQueue @ angular.js:15097(anonymous function) @ angular.js:15113Scope.$eval @ angular.js:16359Scope.$digest @ angular.js:16175Scope.$apply @ angular.js:16467done @ angular.js:10852completeRequest @ angular.js:11050requestLoaded @ angular.js:10991
```
Also, after refreshing the page and logging again, If I choose use the backup I get the following message: Please wait until the data is backed up, but this does not go away and there are still no artworks on the artworks page.

**Comment by budhajeewa** [comment]
@timofeysie I think this issue is fixed with issue #41 .
