### ISSUE TITLE
Artist links open a new logged in page and not the linked to website

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/serene-brushlands#24]
Artist pasge AASD Link and Wiki Link lead back to the logged in page.  They should open a new page on their related sites with the name as the parameter.

**Comment by budhajeewa** [comment]
This is happens because artist data is not available in database. I have uploaded the artwork file to testing site. Now these links are working fine. (eg : http://trifurcata.cf/#/view2/Penny%20Bidd)
