### ISSUE TITLE
Locations layout is not as expected in Safari

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/serene-brushlands#25]
The tiles stack horizontally on Safari 8 running on Mac OSX Yosemite.

**Comment by timofeysie** [comment]
https://www.dropbox.com/s/46jw4tvz4ppvz3t/Screenshot%202016-06-10%2004.57.46.png?dl=0

**Comment by budhajeewa** [comment]
Couldn't check this because I don't have Mac. I Checked on chrome. it work well. This cannot happen because safari and chrome use same core.
