### ISSUE TITLE
Chrome shows nothing but the header drop shadow

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/serene-brushlands#26]
Chrome on Android on an Galaxy Note 4 shows nothing but the top drop shadow.
Chrome Version 51 (64-bit) also shows nothing when running on Mac OSX.

**Comment by budhajeewa** [comment]
@timofeysie I have tested on android device with google chrome. It working fine clear cache and try again. Do the same in Mac OSX too.

**Comment by budhajeewa** [comment]
duplicate issue #57 .So I will close #57 .

**Comment by budhajeewa** [comment]
Unable to reproduce loading issue, disabled fetching libraries from CDN's and moved them to local.

**Comment by timofeysie** [comment]
Explanation regarding why this issue was occurring:
Some libraries fetched from CDN's and it took some time . So I removed those lines and put them in the local folder.I think the fault was app.js file and now I think the issue is fixed in that file,But your broswer still using the faulty app.js file which is in your browser cache.You can see the changes in github merge request.

**Comment by budhajeewa** [comment]
@timofeysie When you face this issue again, Open developer tools of the browser and go to Storage section and take a screenshot of localStorage keys and values send it to me.

**Comment by timofeysie** [comment]
This blank screen issue is caused by Auth0.
