### ISSUE TITLE
The site needs permissions based features

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/serene-brushlands#28]
This is an epic task.  New signups need to be limited to invite only for features such as upload, editing and viewing of full collection info.
Guest login should be allowed via social media for read only and view restricted access.

**Comment by budhajeewa** [comment]
@timofeysie Could you explain more about this task?
As per my understanding you need to create two users
1. admin users
2. regular users

regular users login using social media and they can only view pages. Cannot upload or edit.
For admin users can upload, edit, view information. Is admin users have separate permission levels like one admin user can only change artwork data, another one only can change artist data.

**Comment by timofeysie** [comment]
That's correct regarding 2 roles, user and admin.  I think the list of admin user will be small, ie: you, me and the product owner.  We could add a list of these emails to the env file.  The would be my first idea on how to start with this feature.

**Comment by budhajeewa** [comment]
Okay,

Should the Admin users all have similar privileges, or should there be a system to micromanage each and every permission attached to each admin?

**Comment by timofeysie** [comment]
No, any admin should have the same permissions.

**Comment by budhajeewa** [comment]
Currently i am implementing a permission based authentication system and it also can be use as a role based authentication system.

**How permission based authentication system works.**

- Add specific user emails to a file and add each email's permissions to it.
- User logged in to the "Artapp" and authentication system recognize the current logged in user's permissions.
- Allow and disallow features according to the logged in user's permissions.

In role based authentication system admin can assign roles to user emails and then authentication system allow and disallow functionalities based on logged in user's role.

**Comment by budhajeewa** [comment]
@timofeysie Implemented role based authentication.Fetch the latest repo and check on branch "do#28".You must create a .role.json file for use with this.There is a tmp file for reference.

**Comment by budhajeewa** [comment]
I have restrict the access to locations fro normal users. I don't unclear about valuation and purchase info pages. Is this pages exists now? Can you send me proper list of permissions for the admin and normal users?
