### ISSUE TITLE
Data being loaded again?

### ISSUE THREAD

**Issue by budhajeewa** [timofeysie/serene-brushlands#34]
>Going to an artist shows a loading spinner. It took thirty seconds. If that data was already loaded, why is it being loaded again?

— @timofeysie

**Comment by budhajeewa** [comment]
I didn't get this issue. their is small delay. But it is less than 1 second. Can you check again and let me know status?

**Comment by timofeysie** [comment]
I was unable to reproduce this.  When/if it happens again I will add another comment then.

**Comment by budhajeewa** [comment]
reopen this issue if it happens again
