### ISSUE TITLE
Filter by artist selector needs more artists

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/serene-brushlands#45]
Why are there only a handful of artists in the selector.  I can see that artist in artists is being used, but I know there are a lot more.

**Comment by budhajeewa** [comment]
@timofeysie we need to load all artworks on gallery page for show all artists in that selector and it will take small time to load all artworks from firebase. Is that OK?

**Comment by timofeysie** [comment]
When the user logs in, the collection data is loaded.  So can't you can create an array of artist names then to use in the filter?
