### ISSUE TITLE
Create links from input

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/serene-brushlands#47]
Links entered in on the view2 forms should be shown as links.
For example, I entered a url about Djirrirra Wununurra
I pressed the back button, and the loading spinner came up as the collection was loaded again.  Why did the loader come up again?
I click on another artist, Jessie Hunter, and the loading spinner is shown again while the collection is loaded again.

**Comment by budhajeewa** [comment]
Is the issue is links should be shown as links not button or data is loading again? can you explain this issue?

**Comment by timofeysie** [comment]
This feature is to mainly provide links to content about the artist, so if someone enters a link, it should be clickable after they have added it.  Does that make sense?

**Comment by budhajeewa** [comment]
Yeah,I got it.I implemented this feature.
