### ISSUE TITLE
Perform role checks on the server

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/serene-brushlands#59]
Hide the data for Locations, Insured and Provenance (see issue #28) by filtering that information out in the NodeJS file, and not send that information to the browser where it would be available for all to see.  The same should go for the user roles and sensitive info.

**Comment by budhajeewa** [comment]
@timofeysie We implemented basic mechanism in node for authorize users for tasks.Please fetch the do#59 branch and create a .permissions.json file as it's template file.Then add your email to "manage-user-permissions" array.Then you can see "User Permissions" on navigation bar. We will implement this to all authentication required requests. (I didn't remove previous angular auth system.I will remove it completely after developed this new auth system to adequate level).

**Comment by timofeysie** [comment]
You mean the angular-acl right?  We want to continue to use Auth0.

**Comment by budhajeewa** [comment]
Implementation works successfully. Can you send me a clear list of permissions (What users can do and can't do). So I can add those values to the system.

**Comment by budhajeewa** [comment]
@timofeysie Now you can test it with branch do#59. Create  .permissions.json file and paste content of .permissions.json.tmp and then add your login email to it's manage-user-permissions array.
