### ISSUE TITLE
Differences between document data and application created data

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/serene-brushlands#72]
References numbers should hold the same artwork as the docx file.
Here are some examples of the data differences:
From the doc:
Asset Reference No:  211
Artist: Roy Wiggan
Title: “Ilma”, 1997

From the site:
http://trifurcata.cf/#/view3/211#212

No image
No. 211
Sandhill After Rain 2003
Lily Kelly Napani
122 x 91.5 cm

From the Doc:
Asset Reference No:  213
Artist: Lily Kelly Napangardi
Title: “Sandhill After Rain”, 2003

From the doc:
Asset Reference No:  3
Artist: Dundiway Wanambi
Title: "Wawilak Sister"

From the site:
http://trifurcata.cf/#/view3/2#1

No. 2
"Wawilak Sister"
Dundiway Wanambi
(same image)

**Comment by budhajeewa** [comment]
@timofeysie I think now there is no data deference between doc and website. This wasn't an issue in website data handling, this happened due to uploading wrong artworks doc.You can check and close the issue.
