### ISSUE TITLE
Going to an artwork link does not work

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/serene-brushlands#81]
The app must be able to link directly to artworks.
Going to the following link:
http://trifurcata.cf/#/view3/1
Should lead to the first artwork.
Instead, there is no image, and navigating back and forth does not display other images.

Of course, if the user has not logged in first.  So there are two features here.
A. After being previously logged in, going to a link as shown above should show the correct data.
B. Going to a link without first having a logged in session should lead the user to login (current behaviour), AND THEN lead the user to back to the link they tried to go to.

A is a matter of loading the data if it does not exist on view 3.
B. is more complicated due to Auth0 controlling the logging in process.

**Comment by timofeysie** [comment]
I've noticed that after about 30 seconds the artwork data is loaded.  If this is because the image is slowing down the network call, they text and image should be separated so that we can show the data and then show a small loader for the image to show the user that something is happening.

**Comment by budhajeewa** [comment]
Instead of saving image data in FireBase as text data, It would be better to save image as local file in server.

**Comment by timofeysie** [comment]
Sounds good unless we run out of disk space on DigitalOcean.  How much space will be needed?

**Comment by budhajeewa** [comment]
If we run out of disk space digital ocean offer block storage feature which we can use for any droplet.
https://www.digitalocean.com/pricing/#storage

For the lowest cost droplet have a 20 GB storage

**Comment by budhajeewa** [comment]
@timofeysie Can we try local database like mongoDb instead of Firebase? I think it will improve speed of the data loading.

**Comment by budhajeewa** [comment]
@timofeysie I have checked using mongodb for the app. It increase so much loading speed on app.

**Comment by timofeysie** [comment]
Mongodb is a good idea.  I think also, with the amount of records we are dealing with, the filesystem is also OK.  If you want to use Mongo, that is fine.  Start with a complete feature/API first.  We need to have this individually linked artwork (view 3) working first and then we can start replacing the other API calls.

**Comment by budhajeewa** [comment]
@timofeysie I have created the pull request for the redirect to previous page on login. And I will work on converting database to MongoDb on next week
