### ISSUE TITLE
Organize the select locations and artist names.

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/serene-brushlands#93]
On the locations page, the "Filter by office location" select has repeats in the list.
For example: "St Leonards - Boardroom" appears at least twice, and looks like the same string.

First, group the current locations and order alphabetically.  The same for the artist names.

The fact that there are similar locations with slightly different syntax should be handled in the Word document level.
St Leonards - Office Support
St Leonards -Office Support
When the locations are grouped alphabetically this will aid the normalization process.

The second part of this issue is to create a search input field.  There can be two checkboxes which allow the user to select "Search by artists" and "Search by location" to filter the list using the usual AngularJS filter.

Since the head of the locations page will now have 5 inputs now, use an ng-hide to and a toggle button to open and close this section.

A third part of this issue is the locations shown on the cards should be the same color for the same locations.
As seen in the screenshot attached to [Issue #94](https://github.com/timofeysie/serene-brushlands/issues/94), Brisbane Office is the same string, so should appear as the same color.

**Comment by budhajeewa** [comment]
@timofeysie In third part of this issue cards with same location are need show in same color. 

There are lot of different locations and number of locations can be changed. We cannot generate unique color for each location. 

what we can do is cycle through specific number of colors (may be 5 or 10) or else save color code for each location in database.(this could be save using artwork file or some other way)

**Comment by timofeysie** [comment]
When I first made the background for the locations, I used a limited range of colors.  You can look for the comment /* Cycle thru 0 - 3 different background colors based on location */ in the locations.js file.  There could be more colors, but mainly, this method is not working because the locations are not sorted I think.  The exact same string should have the same color, so this function needs to be re-visited.

**Comment by budhajeewa** [comment]
okay. i will work on it
